static MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "DO NOT MODIFY",
    "auto-generated",
    "autogenerated",
    "Generated by the protocol buffer compiler",
    "This file was automatically generated",
    "Automatically generated file",
];

const WINDOW: usize = 2048;

pub fn is_generated(source: &[u8]) -> bool {
    let window = &source[..source.len().min(WINDOW)];
    let Ok(text) = std::str::from_utf8(window) else {
        return false;
    };
    MARKERS.iter().any(|marker| text.contains(marker))
}
