use tree_sitter::Language;

use crate::model::NodeKind;

pub struct LanguageSpec {
    pub id: &'static str,
    pub type_kinds: &'static [(&'static str, NodeKind)],
    pub function_kinds: &'static [(&'static str, NodeKind)],
    pub field_kinds: &'static [&'static str],
    pub import_kinds: &'static [&'static str],
    pub call_kinds: &'static [&'static str],
    pub constructor_kinds: &'static [&'static str],
    pub name_fields: &'static [&'static str],
    pub parameter_fields: &'static [&'static str],
    pub return_fields: &'static [&'static str],
    pub body_fields: &'static [&'static str],
    pub parameter_kinds: &'static [&'static str],
    pub name_descend: &'static [&'static str],
    pub name_leaf_kinds: &'static [&'static str],
    pub heritage_kinds: &'static [&'static str],
    pub branch_kinds: &'static [&'static str],
    pub loop_kinds: &'static [&'static str],
    pub return_kinds: &'static [&'static str],
    pub throw_kinds: &'static [&'static str],
    pub await_kinds: &'static [&'static str],
    pub receiver_field: &'static str,
    pub impl_kinds: &'static [&'static str],
    pub impl_type_field: &'static str,
    pub receiver_type_field: &'static str,
    pub return_child_kinds: &'static [&'static str],
    pub type_requires_body: bool,
    pub decorator_kinds: &'static [&'static str],
    pub decorator_container_kinds: &'static [&'static str],
}

const COMMON_NAME_LEAVES: &[&str] = &[
    "identifier", "type_identifier", "field_identifier", "simple_identifier", "name",
    "constant", "property_identifier", "package_identifier", "bound_identifier",
];

pub fn language_for(id: &str) -> Option<(Language, &'static LanguageSpec)> {
    let spec = spec_for(id)?;
    let language: Language = match id {
        "python" => tree_sitter_python::LANGUAGE.into(),
        "go" => tree_sitter_go::LANGUAGE.into(),
        "java" => tree_sitter_java::LANGUAGE.into(),
        "csharp" => tree_sitter_c_sharp::LANGUAGE.into(),
        "rust" => tree_sitter_rust::LANGUAGE.into(),
        "ruby" => tree_sitter_ruby::LANGUAGE.into(),
        "php" => tree_sitter_php::LANGUAGE_PHP.into(),
        "c" => tree_sitter_c::LANGUAGE.into(),
        "cpp" => tree_sitter_cpp::LANGUAGE.into(),
        "swift" => tree_sitter_swift::LANGUAGE.into(),
        "kotlin" => tree_sitter_kotlin_ng::LANGUAGE.into(),
        _ => return None,
    };
    Some((language, spec))
}

pub fn spec_for(id: &str) -> Option<&'static LanguageSpec> {
    SPECS.iter().find(|spec| spec.id == id)
}

static SPECS: &[LanguageSpec] = &[
    LanguageSpec {
        id: "python",
        type_kinds: &[("class_definition", NodeKind::Class)],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import_statement", "import_from_statement"],
        call_kinds: &["call"],
        constructor_kinds: &["__init__"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["identifier", "typed_parameter", "default_parameter", "typed_default_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["argument_list"],
        branch_kinds: &["if_statement", "conditional_expression", "match_statement", "boolean_operator"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["raise_statement"],
        await_kinds: &["await"],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["decorator"],
        decorator_container_kinds: &["decorated_definition"],
    },
    LanguageSpec {
        id: "go",
        type_kinds: &[("type_declaration", NodeKind::Class)],
        function_kinds: &[
            ("function_declaration", NodeKind::Function),
            ("method_declaration", NodeKind::Method),
        ],
        field_kinds: &["field_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["result"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration", "variadic_parameter_declaration"],
        name_descend: &["type_spec"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "type_switch_statement", "expression_switch_statement", "select_statement"],
        loop_kinds: &["for_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["go_statement"],
        await_kinds: &[],
        receiver_field: "operand",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "receiver",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
    },
    LanguageSpec {
        id: "java",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("interface_declaration", NodeKind::Interface),
            ("enum_declaration", NodeKind::Enum),
            ("record_declaration", NodeKind::Class),
        ],
        function_kinds: &[
            ("method_declaration", NodeKind::Method),
            ("constructor_declaration", NodeKind::Constructor),
        ],
        field_kinds: &["field_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["method_invocation", "object_creation_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["formal_parameter", "spread_parameter"],
        name_descend: &["variable_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["superclass", "super_interfaces", "extends_interfaces"],
        branch_kinds: &["if_statement", "switch_expression", "ternary_expression"],
        loop_kinds: &["for_statement", "enhanced_for_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["annotation", "marker_annotation"],
        decorator_container_kinds: &["modifiers"],
    },
    LanguageSpec {
        id: "csharp",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("interface_declaration", NodeKind::Interface),
            ("struct_declaration", NodeKind::Class),
            ("record_declaration", NodeKind::Class),
            ("enum_declaration", NodeKind::Enum),
        ],
        function_kinds: &[
            ("method_declaration", NodeKind::Method),
            ("constructor_declaration", NodeKind::Constructor),
            ("local_function_statement", NodeKind::Function),
        ],
        field_kinds: &["field_declaration", "property_declaration"],
        import_kinds: &["using_directive"],
        call_kinds: &["invocation_expression", "object_creation_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["returns", "type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["variable_declaration", "variable_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["base_list"],
        branch_kinds: &["if_statement", "switch_statement", "switch_expression", "conditional_expression"],
        loop_kinds: &["for_statement", "for_each_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement", "throw_expression"],
        await_kinds: &["await_expression"],
        receiver_field: "expression",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["attribute"],
        decorator_container_kinds: &["attribute_list"],
    },
    LanguageSpec {
        id: "rust",
        type_kinds: &[
            ("struct_item", NodeKind::Class),
            ("enum_item", NodeKind::Enum),
            ("trait_item", NodeKind::Interface),
            ("union_item", NodeKind::Class),
            ("type_item", NodeKind::TypeAlias),
        ],
        function_kinds: &[("function_item", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["use_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &["new"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter", "self_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["trait"],
        branch_kinds: &["if_expression", "match_expression", "if_let_expression"],
        loop_kinds: &["for_expression", "while_expression", "loop_expression"],
        return_kinds: &["return_expression"],
        throw_kinds: &["try_expression"],
        await_kinds: &["await_expression"],
        receiver_field: "value",
        impl_kinds: &["impl_item"],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
    },
    LanguageSpec {
        id: "ruby",
        type_kinds: &[("class", NodeKind::Class), ("module", NodeKind::Interface)],
        function_kinds: &[("method", NodeKind::Method), ("singleton_method", NodeKind::Method)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["call"],
        constructor_kinds: &["initialize"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["identifier", "optional_parameter", "keyword_parameter", "splat_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["superclass"],
        branch_kinds: &["if", "unless", "case", "conditional"],
        loop_kinds: &["while", "until", "for"],
        return_kinds: &["return"],
        throw_kinds: &["rescue"],
        await_kinds: &[],
        receiver_field: "receiver",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
    },
    LanguageSpec {
        id: "php",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("interface_declaration", NodeKind::Interface),
            ("trait_declaration", NodeKind::Interface),
            ("enum_declaration", NodeKind::Enum),
        ],
        function_kinds: &[
            ("method_declaration", NodeKind::Method),
            ("function_definition", NodeKind::Function),
        ],
        field_kinds: &["property_declaration"],
        import_kinds: &["namespace_use_declaration"],
        call_kinds: &["function_call_expression", "member_call_expression", "object_creation_expression"],
        constructor_kinds: &["__construct"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["simple_parameter", "variadic_parameter", "property_promotion_parameter"],
        name_descend: &["property_element", "variable_name"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["base_clause", "class_interface_clause"],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression", "match_expression"],
        loop_kinds: &["for_statement", "foreach_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_expression", "throw_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["attribute"],
        decorator_container_kinds: &["attribute_group", "attribute_list"],
    },
    LanguageSpec {
        id: "c",
        type_kinds: &[
            ("struct_specifier", NodeKind::Class),
            ("union_specifier", NodeKind::Class),
            ("enum_specifier", NodeKind::Enum),
        ],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["preproc_include"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration"],
        name_descend: &[
            "function_declarator", "pointer_declarator", "array_declarator",
            "parenthesized_declarator", "init_declarator",
        ],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression"],
        loop_kinds: &["for_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "argument",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: true,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
    },
    LanguageSpec {
        id: "cpp",
        type_kinds: &[
            ("class_specifier", NodeKind::Class),
            ("struct_specifier", NodeKind::Class),
            ("union_specifier", NodeKind::Class),
            ("enum_specifier", NodeKind::Enum),
        ],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["preproc_include"],
        call_kinds: &["call_expression", "new_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration", "optional_parameter_declaration"],
        name_descend: &[
            "function_declarator", "pointer_declarator", "reference_declarator",
            "array_declarator", "parenthesized_declarator", "init_declarator", "qualified_identifier",
        ],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["base_class_clause"],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression"],
        loop_kinds: &["for_statement", "for_range_loop", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &["co_await_expression"],
        receiver_field: "argument",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: true,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
    },
    LanguageSpec {
        id: "swift",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("protocol_declaration", NodeKind::Interface),
        ],
        function_kinds: &[
            ("function_declaration", NodeKind::Function),
            ("init_declaration", NodeKind::Constructor),
            ("protocol_function_declaration", NodeKind::Method),
        ],
        field_kinds: &["property_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["pattern", "value_binding_pattern"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["inheritance_specifier", "type_inheritance_clause"],
        branch_kinds: &["if_statement", "switch_statement", "guard_statement", "ternary_expression"],
        loop_kinds: &["for_statement", "while_statement", "repeat_while_statement"],
        return_kinds: &["control_transfer_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &["await_expression"],
        receiver_field: "target",
        impl_kinds: &["extension_declaration"],
        impl_type_field: "name",
        receiver_type_field: "",
        return_child_kinds: &["user_type", "optional_type", "array_type", "dictionary_type"],
        type_requires_body: false,
        decorator_kinds: &["attribute"],
        decorator_container_kinds: &["modifiers"],
    },
    LanguageSpec {
        id: "kotlin",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("object_declaration", NodeKind::Class),
        ],
        function_kinds: &[("function_declaration", NodeKind::Function)],
        field_kinds: &["property_declaration"],
        import_kinds: &["import", "import_header"],
        call_kinds: &["call_expression"],
        constructor_kinds: &["constructor"],
        name_fields: &["name"],
        parameter_fields: &["function_value_parameters", "parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["variable_declaration"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["delegation_specifier", "constructor_invocation"],
        branch_kinds: &["if_expression", "when_expression"],
        loop_kinds: &["for_statement", "while_statement", "do_while_statement"],
        return_kinds: &["return_expression", "jump_expression"],
        throw_kinds: &["throw_expression"],
        await_kinds: &[],
        receiver_field: "expression",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &["user_type", "nullable_type"],
        type_requires_body: false,
        decorator_kinds: &["annotation"],
        decorator_container_kinds: &["modifiers"],
    },
];
