use tree_sitter::Language;

use crate::model::NodeKind;

pub struct LanguageSpec {
    pub id: &'static str,
    pub type_kinds: &'static [(&'static str, NodeKind)],
    pub function_kinds: &'static [(&'static str, NodeKind)],
    pub field_kinds: &'static [&'static str],
    pub import_kinds: &'static [&'static str],
    pub call_kinds: &'static [&'static str],
    pub constructor_kinds: &'static [&'static str],
    pub name_fields: &'static [&'static str],
    pub parameter_fields: &'static [&'static str],
    pub return_fields: &'static [&'static str],
    pub body_fields: &'static [&'static str],
    pub parameter_kinds: &'static [&'static str],
    pub name_descend: &'static [&'static str],
    pub name_leaf_kinds: &'static [&'static str],
    pub heritage_kinds: &'static [&'static str],
    pub branch_kinds: &'static [&'static str],
    pub loop_kinds: &'static [&'static str],
    pub return_kinds: &'static [&'static str],
    pub throw_kinds: &'static [&'static str],
    pub await_kinds: &'static [&'static str],
    pub receiver_field: &'static str,
    pub impl_kinds: &'static [&'static str],
    pub impl_type_field: &'static str,
    pub receiver_type_field: &'static str,
    pub return_child_kinds: &'static [&'static str],
    pub type_requires_body: bool,
    pub decorator_kinds: &'static [&'static str],
    pub decorator_container_kinds: &'static [&'static str],
    pub name_whole_kinds: &'static [&'static str],
    pub require_name_field: bool,
    pub keyword_kind: &'static str,
    pub keyword_target_field: &'static str,
    pub keyword_types: &'static [&'static str],
    pub keyword_functions: &'static [&'static str],
    pub text_kinds: &'static [&'static str],
}

const BASH_NAME_LEAVES: &[&str] = &["word", "command_name", "variable_name"];
const GDSCRIPT_NAME_LEAVES: &[&str] = &["name", "identifier"];
const CSS_NAME_LEAVES: &[&str] = &["class_name", "id_name", "tag_name", "identifier", "property_name"];
const HASKELL_NAME_LEAVES: &[&str] = &["variable", "name", "module_id", "constructor"];
const GRAPHQL_NAME_LEAVES: &[&str] = &["name"];
const CMAKE_NAME_LEAVES: &[&str] = &["unquoted_argument", "identifier", "argument"];
const MAKE_NAME_LEAVES: &[&str] = &["word", "targets"];
const POWERSHELL_NAME_LEAVES: &[&str] = &["function_name", "simple_name", "command_name_expr"];
const ELM_NAME_LEAVES: &[&str] = &["lower_case_identifier", "upper_case_identifier"];
const ERLANG_NAME_LEAVES: &[&str] = &["atom", "var"];
const OCAML_NAME_LEAVES: &[&str] = &["value_name", "type_constructor", "module_name"];
const NIX_NAME_LEAVES: &[&str] = &["identifier"];
const FORTRAN_NAME_LEAVES: &[&str] = &["identifier", "name"];
const MARKDOWN_NAME_LEAVES: &[&str] = &["inline", "heading_content"];
const XML_NAME_LEAVES: &[&str] = &["Name"];
const HCL_NAME_LEAVES: &[&str] = &["identifier", "template_literal"];

const FSHARP_NAME_LEAVES: &[&str] = &["identifier", "long_identifier"];
const PASCAL_NAME_LEAVES: &[&str] = &["identifier", "moduleName"];
const JSONNET_NAME_LEAVES: &[&str] = &["ident", "string"];
const INI_NAME_LEAVES: &[&str] = &["text", "setting_name", "section_name"];

const ELIXIR_NAME_LEAVES: &[&str] = &["identifier", "alias", "atom"];

const COMMON_NAME_LEAVES: &[&str] = &[
    "identifier", "type_identifier", "field_identifier", "simple_identifier", "name",
    "constant", "property_identifier", "package_identifier", "bound_identifier",
];

pub fn language_for(id: &str) -> Option<(Language, &'static LanguageSpec)> {
    let spec = spec_for(id)?;
    let language: Language = match id {
        "python" => tree_sitter_python::LANGUAGE.into(),
        "go" => tree_sitter_go::LANGUAGE.into(),
        "java" => tree_sitter_java::LANGUAGE.into(),
        "csharp" => tree_sitter_c_sharp::LANGUAGE.into(),
        "rust" => tree_sitter_rust::LANGUAGE.into(),
        "ruby" => tree_sitter_ruby::LANGUAGE.into(),
        "php" => tree_sitter_php::LANGUAGE_PHP.into(),
        "c" => tree_sitter_c::LANGUAGE.into(),
        "cpp" => tree_sitter_cpp::LANGUAGE.into(),
        "swift" => tree_sitter_swift::LANGUAGE.into(),
        "kotlin" => tree_sitter_kotlin_ng::LANGUAGE.into(),
        "bash" | "shell" | "fish" => tree_sitter_bash::LANGUAGE.into(),
        "gdscript" => tree_sitter_gdscript::LANGUAGE.into(),
        "sql" => tree_sitter_sequel::LANGUAGE.into(),
        "css" => tree_sitter_css::LANGUAGE.into(),
        "html" => tree_sitter_html::LANGUAGE.into(),
        "solidity" => tree_sitter_solidity::LANGUAGE.into(),
        "lua" => tree_sitter_lua::LANGUAGE.into(),
        "dart" => tree_sitter_dart::LANGUAGE.into(),
        "scala" => tree_sitter_scala::LANGUAGE.into(),
        "haskell" => tree_sitter_haskell::LANGUAGE.into(),
        "zig" => tree_sitter_zig::LANGUAGE.into(),
        "perl" => tree_sitter_perl::LANGUAGE.into(),
        "groovy" => tree_sitter_groovy::LANGUAGE.into(),
        "proto" => tree_sitter_proto::LANGUAGE.into(),
        "graphql" => tree_sitter_graphql::LANGUAGE.into(),
        "cmake" => tree_sitter_cmake::LANGUAGE.into(),
        "make" => tree_sitter_make::LANGUAGE.into(),
        "powershell" => tree_sitter_powershell::LANGUAGE.into(),
        "elm" => tree_sitter_elm::LANGUAGE.into(),
        "erlang" => tree_sitter_erlang::LANGUAGE.into(),
        "ocaml" => tree_sitter_ocaml::LANGUAGE_OCAML.into(),
        "julia" => tree_sitter_julia::LANGUAGE.into(),
        "starlark" => tree_sitter_starlark::LANGUAGE.into(),
        "nix" => tree_sitter_nix::LANGUAGE.into(),
        "r" => tree_sitter_r::LANGUAGE.into(),
        "objc" => tree_sitter_objc::LANGUAGE.into(),
        "fortran" => tree_sitter_fortran::LANGUAGE.into(),
        "verilog" => tree_sitter_verilog::LANGUAGE.into(),
        "vhdl" => tree_sitter_vhdl::LANGUAGE.into(),
        "gleam" => tree_sitter_gleam::LANGUAGE.into(),
        "markdown" => tree_sitter_md::LANGUAGE.into(),
        "xml" => tree_sitter_xml::LANGUAGE_XML.into(),
        "hcl" | "terraform" => tree_sitter_hcl::LANGUAGE.into(),
        "elixir" => tree_sitter_elixir::LANGUAGE.into(),
        "fsharp" => tree_sitter_fsharp::LANGUAGE_FSHARP.into(),
        "crystal" => tree_sitter_crystal::LANGUAGE.into(),
        "nim" => tree_sitter_nim::LANGUAGE.into(),
        "v" => tree_sitter_v::LANGUAGE.into(),
        "d" => tree_sitter_d::LANGUAGE.into(),
        "pascal" => tree_sitter_pascal::LANGUAGE.into(),
        "ada" => tree_sitter_ada::LANGUAGE.into(),
        "matlab" => tree_sitter_matlab::LANGUAGE.into(),
        "glsl" => tree_sitter_glsl::LANGUAGE_GLSL.into(),
        "hlsl" => tree_sitter_hlsl::LANGUAGE_HLSL.into(),
        "odin" => tree_sitter_odin::LANGUAGE.into(),
        "jsonnet" => tree_sitter_jsonnet::LANGUAGE.into(),
        "ini" => tree_sitter_ini::LANGUAGE.into(),
        "svelte" => tree_sitter_svelte_ng::LANGUAGE.into(),
        "erb" => tree_sitter_embedded_template::LANGUAGE.into(),
        "racket" => tree_sitter_racket::LANGUAGE.into(),
        "scheme" => tree_sitter_scheme::LANGUAGE.into(),
        "commonlisp" => tree_sitter_commonlisp::LANGUAGE_COMMONLISP.into(),
        _ => return None,
    };
    Some((language, spec))
}

pub fn spec_for(id: &str) -> Option<&'static LanguageSpec> {
    let id = match id {
        "shell" | "fish" => "bash",
        "terraform" => "hcl",
        other => other,
    };
    SPECS.iter().find(|spec| spec.id == id)
}

static SPECS: &[LanguageSpec] = &[
    LanguageSpec {
        id: "elixir",
        type_kinds: &[],
        function_kinds: &[],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["target"],
        parameter_fields: &["arguments"],
        return_fields: &[],
        body_fields: &["do_block"],
        parameter_kinds: &["identifier"],
        name_descend: &[],
        name_leaf_kinds: ELIXIR_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "target",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "call",
        keyword_target_field: "target",
        keyword_types: &["defmodule", "defprotocol", "defimpl", "defstruct"],
        keyword_functions: &["def", "defp", "defmacro", "defmacrop", "defdelegate"],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "fsharp",
        type_kinds: &[("record_type_defn", NodeKind::Class), ("union_type_defn", NodeKind::Class)],
        function_kinds: &[("function_or_value_defn", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import_decl", "open"],
        call_kinds: &["application_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["type_name", "function_declaration_left", "long_identifier", "long_identifier_or_op"],
        name_leaf_kinds: FSHARP_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "crystal",
        type_kinds: &[("class_declaration", NodeKind::Class), ("module_declaration", NodeKind::Interface), ("struct_declaration", NodeKind::Class)],
        function_kinds: &[("method_definition", NodeKind::Method)],
        field_kinds: &[],
        import_kinds: &["require"],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if", "unless", "case"],
        loop_kinds: &["while", "until"],
        return_kinds: &["return"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "receiver",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "nim",
        type_kinds: &[("type_declaration", NodeKind::Class)],
        function_kinds: &[("proc_declaration", NodeKind::Function), ("func_declaration", NodeKind::Function), ("method_declaration", NodeKind::Method)],
        field_kinds: &[],
        import_kinds: &["import_statement"],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if", "case"],
        loop_kinds: &["while", "for"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "v",
        type_kinds: &[("struct_declaration", NodeKind::Class), ("interface_declaration", NodeKind::Interface), ("enum_declaration", NodeKind::Enum)],
        function_kinds: &[("function_declaration", NodeKind::Function)],
        field_kinds: &["struct_field_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["result"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_expression", "match_expression"],
        loop_kinds: &["for_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "operand",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "receiver",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "d",
        type_kinds: &[("class_declaration", NodeKind::Class), ("struct_declaration", NodeKind::Class), ("interface_declaration", NodeKind::Interface)],
        function_kinds: &[("function_declaration", NodeKind::Function)],
        field_kinds: &["variable_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "pascal",
        type_kinds: &[("declType", NodeKind::Class)],
        function_kinds: &[("declProc", NodeKind::Function), ("declFunc", NodeKind::Function)],
        field_kinds: &["declField"],
        import_kinds: &["uses"],
        call_kinds: &["exprCall"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["args"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["declArg"],
        name_descend: &[],
        name_leaf_kinds: PASCAL_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if"],
        loop_kinds: &["while", "for", "repeat"],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "ada",
        type_kinds: &[("full_type_declaration", NodeKind::Class), ("package_declaration", NodeKind::Interface)],
        function_kinds: &[("subprogram_declaration", NodeKind::Function), ("subprogram_body", NodeKind::Function)],
        field_kinds: &["component_declaration"],
        import_kinds: &["with_clause"],
        call_kinds: &["function_call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["formal_part"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter_specification"],
        name_descend: &["function_specification", "procedure_specification"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "matlab",
        type_kinds: &[],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["function_call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["function_arguments"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["identifier"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "glsl",
        type_kinds: &[("struct_specifier", NodeKind::Class)],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["preproc_include"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration"],
        name_descend: &["function_declarator", "pointer_declarator", "init_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "argument",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: true,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "hlsl",
        type_kinds: &[("struct_specifier", NodeKind::Class)],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["preproc_include"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration"],
        name_descend: &["function_declarator", "pointer_declarator", "init_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "argument",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: true,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "odin",
        type_kinds: &[("struct_declaration", NodeKind::Class), ("enum_declaration", NodeKind::Enum), ("union_declaration", NodeKind::Class)],
        function_kinds: &[("procedure_declaration", NodeKind::Function)],
        field_kinds: &["field"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "jsonnet",
        type_kinds: &[("object", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &["field"],
        import_kinds: &[],
        call_kinds: &["suffix_apply"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["param"],
        name_descend: &["field_name"],
        name_leaf_kinds: JSONNET_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "ini",
        type_kinds: &[("section", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &["setting"],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["section_name", "setting_name"],
        name_leaf_kinds: INI_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "svelte",
        type_kinds: &[],
        function_kinds: &[],
        field_kinds: &[],
        import_kinds: &["script_element", "style_element"],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: XML_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "erb",
        type_kinds: &[],
        function_kinds: &[],
        field_kinds: &[],
        import_kinds: &["directive"],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "racket",
        type_kinds: &[],
        function_kinds: &[("list", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "scheme",
        type_kinds: &[],
        function_kinds: &[("list", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "commonlisp",
        type_kinds: &[],
        function_kinds: &[("defun", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },

    LanguageSpec {
        id: "html",
        type_kinds: &[],
        function_kinds: &[],
        field_kinds: &[],
        import_kinds: &["script_element", "style_element"],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &[],
        return_fields: &[],
        body_fields: &[],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: XML_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },

    LanguageSpec {
        id: "bash",
        type_kinds: &[],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["command"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: BASH_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "case_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "name",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "gdscript",
        type_kinds: &[("class_name_statement", NodeKind::Class), ("class_definition", NodeKind::Class)],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["variable_statement"],
        import_kinds: &[],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["identifier", "typed_parameter", "default_parameter", "typed_default_parameter"],
        name_descend: &[],
        name_leaf_kinds: GDSCRIPT_NAME_LEAVES,
        heritage_kinds: &["extends_statement"],
        branch_kinds: &["if_statement", "match_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "sql",
        type_kinds: &[("create_table", NodeKind::Class), ("create_view", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &["column_definition"],
        import_kinds: &[],
        call_kinds: &["invocation"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["object_reference"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "css",
        type_kinds: &[("rule_set", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &["declaration"],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["selectors", "class_selector", "id_selector", "tag_name"],
        name_leaf_kinds: CSS_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "solidity",
        type_kinds: &[("contract_declaration", NodeKind::Class), ("interface_declaration", NodeKind::Interface), ("library_declaration", NodeKind::Class), ("struct_declaration", NodeKind::Class), ("enum_declaration", NodeKind::Enum)],
        function_kinds: &[("function_definition", NodeKind::Function), ("modifier_definition", NodeKind::Function), ("constructor_definition", NodeKind::Constructor)],
        field_kinds: &["state_variable_declaration", "struct_member"],
        import_kinds: &["import_directive"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["inheritance_specifier"],
        branch_kinds: &["if_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["revert_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "lua",
        type_kinds: &[],
        function_kinds: &[("function_declaration", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["function_call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["identifier"],
        name_descend: &["dot_index_expression", "method_index_expression"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement"],
        loop_kinds: &["for_statement", "for_numeric_statement", "while_statement", "repeat_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "table",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &["dot_index_expression", "method_index_expression"],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "dart",
        type_kinds: &[("class_definition", NodeKind::Class), ("class_declaration", NodeKind::Class), ("mixin_declaration", NodeKind::Interface), ("enum_declaration", NodeKind::Enum), ("extension_declaration", NodeKind::Class)],
        function_kinds: &[("method_declaration", NodeKind::Method)],
        field_kinds: &["declaration"],
        import_kinds: &["import_or_export"],
        call_kinds: &["call_expression", "new_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters", "formal_parameter_list"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["formal_parameter", "optional_formal_parameters"],
        name_descend: &["method_signature", "function_signature", "initialized_identifier_list", "initialized_identifier"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["superclass"],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression"],
        loop_kinds: &["for_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_expression"],
        await_kinds: &["await_expression"],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "scala",
        type_kinds: &[("class_definition", NodeKind::Class), ("object_definition", NodeKind::Class), ("trait_definition", NodeKind::Interface), ("enum_definition", NodeKind::Enum)],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["val_definition", "var_definition"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "pattern"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["extends_clause"],
        branch_kinds: &["if_expression", "match_expression"],
        loop_kinds: &["for_expression", "while_expression"],
        return_kinds: &["return_expression"],
        throw_kinds: &["throw_expression"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "haskell",
        type_kinds: &[("data_type", NodeKind::Class), ("newtype", NodeKind::Class), ("type_synomym", NodeKind::TypeAlias), ("class", NodeKind::Interface)],
        function_kinds: &[("function", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import"],
        call_kinds: &["apply"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: HASKELL_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "function",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: true,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "zig",
        type_kinds: &[("struct_declaration", NodeKind::Class), ("enum_declaration", NodeKind::Enum), ("union_declaration", NodeKind::Class)],
        function_kinds: &[("function_declaration", NodeKind::Function)],
        field_kinds: &["container_field"],
        import_kinds: &[],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "if_expression", "switch_expression"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_expression"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "function",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "perl",
        type_kinds: &[],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["use_statement"],
        call_kinds: &["function_call_expression", "method_call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["conditional_statement"],
        loop_kinds: &["loop_statement"],
        return_kinds: &["return_expression"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "groovy",
        type_kinds: &[("class_declaration", NodeKind::Class), ("interface_declaration", NodeKind::Interface), ("enum_declaration", NodeKind::Enum)],
        function_kinds: &[("method_declaration", NodeKind::Method), ("constructor_declaration", NodeKind::Constructor)],
        field_kinds: &["field_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["method_invocation", "object_creation_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters", "formal_parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["formal_parameter"],
        name_descend: &["variable_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["superclass", "super_interfaces"],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement", "enhanced_for_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "proto",
        type_kinds: &[("message", NodeKind::Class), ("service", NodeKind::Interface), ("enum", NodeKind::Enum)],
        function_kinds: &[("rpc", NodeKind::Method)],
        field_kinds: &["field"],
        import_kinds: &["import"],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["message_name", "service_name", "rpc_name", "enum_name"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "graphql",
        type_kinds: &[("object_type_definition", NodeKind::Class), ("interface_type_definition", NodeKind::Interface), ("enum_type_definition", NodeKind::Enum), ("input_object_type_definition", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &["field_definition", "input_value_definition"],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: GRAPHQL_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "cmake",
        type_kinds: &[],
        function_kinds: &[("function_def", NodeKind::Function), ("macro_def", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["normal_command"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["function_command", "macro_command", "argument_list", "argument"],
        name_leaf_kinds: CMAKE_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_condition"],
        loop_kinds: &["foreach_loop", "while_loop"],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "make",
        type_kinds: &[],
        function_kinds: &[("rule", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["targets"],
        name_leaf_kinds: MAKE_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "powershell",
        type_kinds: &[],
        function_kinds: &[("function_statement", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["command"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["param_block"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["script_parameter"],
        name_descend: &[],
        name_leaf_kinds: POWERSHELL_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement", "foreach_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "elm",
        type_kinds: &[("type_declaration", NodeKind::Class), ("type_alias_declaration", NodeKind::TypeAlias)],
        function_kinds: &[("value_declaration", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import_clause"],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["function_declaration_left"],
        name_leaf_kinds: ELM_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "erlang",
        type_kinds: &[],
        function_kinds: &[("fun_decl", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["module_attribute"],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["function_clause"],
        name_leaf_kinds: ERLANG_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "expr",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "ocaml",
        type_kinds: &[("type_definition", NodeKind::TypeAlias)],
        function_kinds: &[("value_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["open_module"],
        call_kinds: &["application_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "pattern"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["let_binding", "type_binding"],
        name_leaf_kinds: OCAML_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "julia",
        type_kinds: &[("struct_definition", NodeKind::Class), ("abstract_definition", NodeKind::Interface)],
        function_kinds: &[("function_definition", NodeKind::Function), ("short_function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import_statement", "using_statement"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["type_head", "signature", "call_expression"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "starlark",
        type_kinds: &[],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["identifier", "typed_parameter", "default_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement"],
        loop_kinds: &["for_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "nix",
        type_kinds: &[],
        function_kinds: &[("function_expression", NodeKind::Function)],
        field_kinds: &["binding"],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["formal"],
        name_descend: &["attrpath"],
        name_leaf_kinds: NIX_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "r",
        type_kinds: &[],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "function",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "objc",
        type_kinds: &[("class_interface", NodeKind::Class), ("class_implementation", NodeKind::Class), ("protocol_declaration", NodeKind::Interface)],
        function_kinds: &[("method_definition", NodeKind::Method), ("method_declaration", NodeKind::Method)],
        field_kinds: &["property_declaration", "field_declaration"],
        import_kinds: &["preproc_import", "preproc_include"],
        call_kinds: &["call_expression", "message_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "fortran",
        type_kinds: &[("derived_type_definition", NodeKind::Class), ("module", NodeKind::Interface)],
        function_kinds: &[("function", NodeKind::Function), ("subroutine", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["subroutine_call", "call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: FORTRAN_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "select_case_statement"],
        loop_kinds: &["do_loop_statement"],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "verilog",
        type_kinds: &[("module_declaration", NodeKind::Class)],
        function_kinds: &[("function_declaration", NodeKind::Function), ("task_declaration", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "vhdl",
        type_kinds: &[("entity_declaration", NodeKind::Class), ("architecture_body", NodeKind::Class)],
        function_kinds: &[("subprogram_body", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "gleam",
        type_kinds: &[("type_definition", NodeKind::Class)],
        function_kinds: &[("function", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import"],
        call_kinds: &["function_call"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["function_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "markdown",
        type_kinds: &[("section", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["atx_heading"],
        name_leaf_kinds: MARKDOWN_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "xml",
        type_kinds: &[("element", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &["STag", "Name"],
        name_leaf_kinds: XML_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &["content"],
    },
    LanguageSpec {
        id: "hcl",
        type_kinds: &[("block", NodeKind::Class)],
        function_kinds: &[],
        field_kinds: &["attribute"],
        import_kinds: &[],
        call_kinds: &[],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &[],
        name_descend: &[],
        name_leaf_kinds: HCL_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &[],
        loop_kinds: &[],
        return_kinds: &[],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },

    LanguageSpec {
        id: "python",
        type_kinds: &[("class_definition", NodeKind::Class)],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &[],
        import_kinds: &["import_statement", "import_from_statement"],
        call_kinds: &["call"],
        constructor_kinds: &["__init__"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["identifier", "typed_parameter", "default_parameter", "typed_default_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["argument_list"],
        branch_kinds: &["if_statement", "conditional_expression", "match_statement", "boolean_operator"],
        loop_kinds: &["for_statement", "while_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["raise_statement"],
        await_kinds: &["await"],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["decorator"],
        decorator_container_kinds: &["decorated_definition"],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "go",
        type_kinds: &[("type_declaration", NodeKind::Class)],
        function_kinds: &[
            ("function_declaration", NodeKind::Function),
            ("method_declaration", NodeKind::Method),
        ],
        field_kinds: &["field_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["result"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration", "variadic_parameter_declaration"],
        name_descend: &["type_spec"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "type_switch_statement", "expression_switch_statement", "select_statement"],
        loop_kinds: &["for_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["go_statement"],
        await_kinds: &[],
        receiver_field: "operand",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "receiver",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "java",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("interface_declaration", NodeKind::Interface),
            ("enum_declaration", NodeKind::Enum),
            ("record_declaration", NodeKind::Class),
        ],
        function_kinds: &[
            ("method_declaration", NodeKind::Method),
            ("constructor_declaration", NodeKind::Constructor),
        ],
        field_kinds: &["field_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["method_invocation", "object_creation_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["formal_parameter", "spread_parameter"],
        name_descend: &["variable_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["superclass", "super_interfaces", "extends_interfaces"],
        branch_kinds: &["if_statement", "switch_expression", "ternary_expression"],
        loop_kinds: &["for_statement", "enhanced_for_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["annotation", "marker_annotation"],
        decorator_container_kinds: &["modifiers"],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "csharp",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("interface_declaration", NodeKind::Interface),
            ("struct_declaration", NodeKind::Class),
            ("record_declaration", NodeKind::Class),
            ("enum_declaration", NodeKind::Enum),
        ],
        function_kinds: &[
            ("method_declaration", NodeKind::Method),
            ("constructor_declaration", NodeKind::Constructor),
            ("local_function_statement", NodeKind::Function),
        ],
        field_kinds: &["field_declaration", "property_declaration"],
        import_kinds: &["using_directive"],
        call_kinds: &["invocation_expression", "object_creation_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["returns", "type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["variable_declaration", "variable_declarator"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["base_list"],
        branch_kinds: &["if_statement", "switch_statement", "switch_expression", "conditional_expression"],
        loop_kinds: &["for_statement", "for_each_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement", "throw_expression"],
        await_kinds: &["await_expression"],
        receiver_field: "expression",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["attribute"],
        decorator_container_kinds: &["attribute_list"],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "rust",
        type_kinds: &[
            ("struct_item", NodeKind::Class),
            ("enum_item", NodeKind::Enum),
            ("trait_item", NodeKind::Interface),
            ("union_item", NodeKind::Class),
            ("type_item", NodeKind::TypeAlias),
        ],
        function_kinds: &[("function_item", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["use_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &["new"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter", "self_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["trait"],
        branch_kinds: &["if_expression", "match_expression", "if_let_expression"],
        loop_kinds: &["for_expression", "while_expression", "loop_expression"],
        return_kinds: &["return_expression"],
        throw_kinds: &["try_expression"],
        await_kinds: &["await_expression"],
        receiver_field: "value",
        impl_kinds: &["impl_item"],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "ruby",
        type_kinds: &[("class", NodeKind::Class), ("module", NodeKind::Interface)],
        function_kinds: &[("method", NodeKind::Method), ("singleton_method", NodeKind::Method)],
        field_kinds: &[],
        import_kinds: &[],
        call_kinds: &["call"],
        constructor_kinds: &["initialize"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["identifier", "optional_parameter", "keyword_parameter", "splat_parameter"],
        name_descend: &[],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["superclass"],
        branch_kinds: &["if", "unless", "case", "conditional"],
        loop_kinds: &["while", "until", "for"],
        return_kinds: &["return"],
        throw_kinds: &["rescue"],
        await_kinds: &[],
        receiver_field: "receiver",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "php",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("interface_declaration", NodeKind::Interface),
            ("trait_declaration", NodeKind::Interface),
            ("enum_declaration", NodeKind::Enum),
        ],
        function_kinds: &[
            ("method_declaration", NodeKind::Method),
            ("function_definition", NodeKind::Function),
        ],
        field_kinds: &["property_declaration"],
        import_kinds: &["namespace_use_declaration"],
        call_kinds: &["function_call_expression", "member_call_expression", "nullsafe_member_call_expression", "scoped_call_expression", "object_creation_expression"],
        constructor_kinds: &["__construct"],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["simple_parameter", "variadic_parameter", "property_promotion_parameter"],
        name_descend: &["property_element", "variable_name"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["base_clause", "class_interface_clause"],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression", "match_expression"],
        loop_kinds: &["for_statement", "foreach_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_expression", "throw_statement"],
        await_kinds: &[],
        receiver_field: "object",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: false,
        decorator_kinds: &["attribute"],
        decorator_container_kinds: &["attribute_group", "attribute_list"],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "c",
        type_kinds: &[
            ("struct_specifier", NodeKind::Class),
            ("union_specifier", NodeKind::Class),
            ("enum_specifier", NodeKind::Enum),
        ],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["preproc_include"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration"],
        name_descend: &[
            "function_declarator", "pointer_declarator", "array_declarator",
            "parenthesized_declarator", "init_declarator",
        ],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &[],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression"],
        loop_kinds: &["for_statement", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &[],
        await_kinds: &[],
        receiver_field: "argument",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: true,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "cpp",
        type_kinds: &[
            ("class_specifier", NodeKind::Class),
            ("struct_specifier", NodeKind::Class),
            ("union_specifier", NodeKind::Class),
            ("enum_specifier", NodeKind::Enum),
        ],
        function_kinds: &[("function_definition", NodeKind::Function)],
        field_kinds: &["field_declaration"],
        import_kinds: &["preproc_include"],
        call_kinds: &["call_expression", "new_expression"],
        constructor_kinds: &[],
        name_fields: &["name", "declarator"],
        parameter_fields: &["parameters"],
        return_fields: &["type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter_declaration", "optional_parameter_declaration"],
        name_descend: &[
            "function_declarator", "pointer_declarator", "reference_declarator",
            "array_declarator", "parenthesized_declarator", "init_declarator", "qualified_identifier",
        ],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["base_class_clause"],
        branch_kinds: &["if_statement", "switch_statement", "conditional_expression"],
        loop_kinds: &["for_statement", "for_range_loop", "while_statement", "do_statement"],
        return_kinds: &["return_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &["co_await_expression"],
        receiver_field: "argument",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &[],
        type_requires_body: true,
        decorator_kinds: &[],
        decorator_container_kinds: &[],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "swift",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("protocol_declaration", NodeKind::Interface),
        ],
        function_kinds: &[
            ("function_declaration", NodeKind::Function),
            ("init_declaration", NodeKind::Constructor),
            ("protocol_function_declaration", NodeKind::Method),
        ],
        field_kinds: &["property_declaration"],
        import_kinds: &["import_declaration"],
        call_kinds: &["call_expression"],
        constructor_kinds: &[],
        name_fields: &["name"],
        parameter_fields: &["parameters"],
        return_fields: &[],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["pattern", "value_binding_pattern"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["inheritance_specifier", "type_inheritance_clause"],
        branch_kinds: &["if_statement", "switch_statement", "guard_statement", "ternary_expression"],
        loop_kinds: &["for_statement", "while_statement", "repeat_while_statement"],
        return_kinds: &["control_transfer_statement"],
        throw_kinds: &["throw_statement"],
        await_kinds: &["await_expression"],
        receiver_field: "target",
        impl_kinds: &["extension_declaration"],
        impl_type_field: "name",
        receiver_type_field: "",
        return_child_kinds: &["user_type", "optional_type", "array_type", "dictionary_type"],
        type_requires_body: false,
        decorator_kinds: &["attribute"],
        decorator_container_kinds: &["modifiers"],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
    LanguageSpec {
        id: "kotlin",
        type_kinds: &[
            ("class_declaration", NodeKind::Class),
            ("object_declaration", NodeKind::Class),
        ],
        function_kinds: &[("function_declaration", NodeKind::Function)],
        field_kinds: &["property_declaration"],
        import_kinds: &["import", "import_header"],
        call_kinds: &["call_expression"],
        constructor_kinds: &["constructor"],
        name_fields: &["name"],
        parameter_fields: &["function_value_parameters", "parameters"],
        return_fields: &["return_type"],
        body_fields: &["body"],
        parameter_kinds: &["parameter"],
        name_descend: &["variable_declaration"],
        name_leaf_kinds: COMMON_NAME_LEAVES,
        heritage_kinds: &["delegation_specifier", "constructor_invocation"],
        branch_kinds: &["if_expression", "when_expression"],
        loop_kinds: &["for_statement", "while_statement", "do_while_statement"],
        return_kinds: &["return_expression", "jump_expression"],
        throw_kinds: &["throw_expression"],
        await_kinds: &[],
        receiver_field: "expression",
        impl_kinds: &[],
        impl_type_field: "type",
        receiver_type_field: "",
        return_child_kinds: &["user_type", "nullable_type"],
        type_requires_body: false,
        decorator_kinds: &["annotation"],
        decorator_container_kinds: &["modifiers"],
        name_whole_kinds: &[],
        require_name_field: false,
        keyword_kind: "",
        keyword_target_field: "target",
        keyword_types: &[],
        keyword_functions: &[],
        text_kinds: &[],
    },
];
