export const LanguageAnalyzers = {
  python: "PythonAnalyzer",
  javascript: "TypeScriptJavaScriptAnalyzer",
  typescript: "TypeScriptJavaScriptAnalyzer",
  java: "JavaAnalyzer",
  csharp: "CSharpAnalyzer",
  vb: "CSharpAnalyzer",
  go: "GoAnalyzer",
  rust: "RustAnalyzer",
  php: "PHPAnalyzer",
  ruby: "RubyAnalyzer",
  dart: "DartAnalyzer",
  terraform: "TerraformAnalyzer",
  cloudformation: "CloudFormationAnalyzer",
  sql: "SqlSchemaAnalyzer",
  c: "CCppAnalyzer",
  cpp: "CCppAnalyzer",
  kotlin: "KotlinAnalyzer",
  swift: "SwiftAnalyzer",
  solidity: "SolidityAnalyzer",
  elixir: "ElixirAnalyzer",
  shell: "ShellAnalyzer",
  bash: "ShellAnalyzer",
  protobuf: "ProtobufAnalyzer",
  proto: "ProtobufAnalyzer",
  wsdl: "SoapWsdlAnalyzer",
  xsd: "SoapWsdlAnalyzer",
} as const;
