import { Box, Chip, Stack, Tooltip, Typography } from '@mui/material';
import type { WorkspaceAnalysisResponse } from '@/shared/api/index';
import { formatCount } from './workspaceHelpers';
import { formatRelativeTime } from '@/app/Dashboard/formatRelativeTime';
import { StatGlyphIcon, type StatGlyph } from '@/shared/components/icons/StatGlyphIcon';

type WorkspaceGraph = NonNullable<WorkspaceAnalysisResponse['analysis']>;

export interface WorkspaceHeaderProps {
  name: string;
  narrative?: WorkspaceGraph['workspace_narrative'];
  generatedAt?: string;
  enrichmentStatus?: WorkspaceAnalysisResponse['enrichment'];
  lastAttempt?: WorkspaceAnalysisResponse['last_attempt'];
  stats: { repositories?: number; capabilities?: number; flows?: number; entities?: number; contributors?: number };
}

const statusColor: Record<string, string> = {
  ai: 'success.main',
  degraded: 'warning.main',
  error: 'error.main',
  skipped: 'text.disabled',
  pending: 'text.disabled',
};

export function WorkspaceHeader({ name, narrative, generatedAt, enrichmentStatus, lastAttempt, stats }: WorkspaceHeaderProps) {
  const relative = formatRelativeTime(generatedAt);
  const dotColor = statusColor[enrichmentStatus?.status ?? ''] ?? 'text.disabled';
  const tooltipText = enrichmentTooltip(enrichmentStatus, lastAttempt);

  return (
    <Stack spacing={2}>
      {relative ? (
        <Tooltip title={tooltipText} arrow placement="right">
          <Stack direction="row" spacing={1} sx={{ alignItems: 'center', width: 'fit-content', cursor: 'default' }}>
            <Box sx={{ width: 6, height: 6, borderRadius: '50%', bgcolor: dotColor }} />
            <Typography variant="caption" color="text.secondary">
              Updated {relative}
            </Typography>
          </Stack>
        </Tooltip>
      ) : null}

      <Stack direction="row" spacing={1.5} sx={{ alignItems: 'center' }}>
        <Typography variant="h4" component="h1">
          {name}
        </Typography>
        {/* No single source repository backs a workspace, so this is an honest
            generic label rather than a fabricated link. */}
        <Chip size="small" variant="outlined" label="Workspace" />
      </Stack>

      {narrative?.description ? (
        <Typography variant="body2" color="text.secondary" sx={{ maxWidth: 900 }}>
          {narrative.description}
        </Typography>
      ) : (
        <Typography variant="body2" color="text.disabled" sx={{ maxWidth: 900 }}>
          No narrative yet — the workspace summary is written once enrichment finishes.
        </Typography>
      )}

      <Stack direction="row" spacing={2} sx={{ flexWrap: 'wrap' }}>
        <Stat glyph="repositories" value={stats.repositories} label="Repositories" />
        <Stat glyph="capabilities" value={stats.capabilities} label="Capabilities" />
        <Stat glyph="flows" value={stats.flows} label="Flows" />
        <Stat glyph="entities" value={stats.entities} label="Entities" />
        <Stat glyph="contributors" value={stats.contributors} label="Contributors" />
      </Stack>
    </Stack>
  );
}

function Stat({ glyph, value, label }: { glyph: StatGlyph; value: number | undefined; label: string }) {
  return (
    <Stack direction="row" spacing={1} sx={{ alignItems: 'center' }}>
      <Box sx={{ display: 'flex' }}>
        <StatGlyphIcon glyph={glyph} size={16} />
      </Box>
      <Stack direction="row" spacing={0.5} sx={{ alignItems: 'center' }}>
        <Typography variant="caption" sx={{ fontWeight: 600 }}>
          {formatCount(value)}
        </Typography>
        <Typography variant="caption" color="text.secondary">
          {label}
        </Typography>
      </Stack>
    </Stack>
  );
}

function enrichmentTooltip(
  enrichment: WorkspaceAnalysisResponse['enrichment'],
  lastAttempt: WorkspaceAnalysisResponse['last_attempt'],
): string {
  if (lastAttempt?.state === 'failed') return `Last rebuild failed: ${lastAttempt.reason ?? 'unknown reason'}`;
  if (enrichment?.status === 'degraded') return `Narrative degraded: ${enrichment.reason ?? enrichment.error ?? 'unknown reason'}`;
  if (enrichment?.status === 'error') return `Narrative error: ${enrichment.error ?? 'unknown error'}`;
  if (enrichment?.status === 'pending') return 'Narrative is still being generated.';
  if (enrichment?.status === 'ai') return 'Narrative generated by AI comprehension.';
  return 'Freshness of the last workspace analysis.';
}
