jest.unmock('fs-extra');
jest.unmock('fs');
jest.unmock('glob');

import * as fs from 'fs-extra';
import * as os from 'os';
import * as path from 'path';
import { GoAnalyzer } from '../../analyzer/languages/go-analyzer';
import { AnalyzerOrchestrator } from '../../analyzer/core/orchestrator';
import type { CASEntryPoint, CASNode } from '../../types/cas.types';

async function analyzeSource(root: string, relativePath: string, source: string): Promise<CASNode[]> {
  const fullPath = path.join(root, relativePath);
  await fs.outputFile(fullPath, source);
  const nodes: CASNode[] = [];
  await (new GoAnalyzer() as any).analyzeGoFile(
    fullPath,
    relativePath,
    nodes,
    [],
    [],
    [],
    new Map(),
    { projectPath: root },
  );
  return nodes;
}

describe('Go generated source provenance', () => {
  let root: string;

  beforeEach(async () => {
    root = await fs.mkdtemp(path.join(os.tmpdir(), 'klauro-go-generated-'));
  });

  afterEach(async () => {
    await fs.remove(root);
  });

  test('marks every node emitted from a standard generated Go file without removing graph nodes', async () => {
    const nodes = await analyzeSource(root, 'proto/gen/service.pb.go', [
      '// Code generated by protoc-gen-go. DO NOT EDIT.',
      'package api',
      'type Memo struct { ID string }',
      'func (m *Memo) GetID() string { return m.ID }',
    ].join('\n'));

    expect(nodes.length).toBeGreaterThan(2);
    expect(nodes.every(node => node.metadata?.is_generated === true)).toBe(true);
    expect(nodes.some(node => node.name === 'Memo')).toBe(true);
    expect(nodes.some(node => node.name === 'GetID')).toBe(true);
  });

  test('does not infer generated provenance from an authored gen directory path', async () => {

    const nodes = await analyzeSource(root, 'internal/gen/authored.go', [
      'package gen',
      'type MemoService struct {}',
      'func CreateMemo() {}',
    ].join('\n'));

    expect(nodes.length).toBeGreaterThan(1);
    expect(nodes.every(node => node.metadata?.is_generated !== true)).toBe(true);
  });

  test('does not accept a generated marker placed after authored Go code', async () => {
    const nodes = await analyzeSource(root, 'internal/service.go', [
      'package service',
      '// Code generated by a misleading tool. DO NOT EDIT.',
      'func CreateMemo() {}',
    ].join('\n'));

    expect(nodes.length).toBeGreaterThan(1);
    expect(nodes.every(node => node.metadata?.is_generated !== true)).toBe(true);
  });

  test('existing product filtering excludes generated handlers while retaining authored server evidence', async () => {
    const generated = await analyzeSource(root, 'proto/gen/service.pb.go', [
      '// Code generated by protoc-gen-go. DO NOT EDIT.',
      'package api',
      'func CreateMemo() {}',
    ].join('\n'));
    const authored = await analyzeSource(root, 'internal/gen/server.go', [
      'package gen',
      'func CreateMemo() {}',
    ].join('\n'));
    const generatedHandler = generated.find(node => node.name === 'CreateMemo')!;
    const authoredHandler = authored.find(node => node.name === 'CreateMemo')!;
    const entries = [
      {
        id: 'generated-entry',
        source_node: generatedHandler.id,
        type: 'http',
        name: 'POST /generated-memos',
        trigger: { method: 'POST', path: '/generated-memos' },
        handler: { node_id: generatedHandler.id, file: 'proto/gen/service.pb.go' },
      },
      {
        id: 'authored-entry',
        source_node: authoredHandler.id,
        type: 'http',
        name: 'POST /memos',
        trigger: { method: 'POST', path: '/memos' },
        handler: { node_id: authoredHandler.id, file: 'internal/gen/server.go' },
      },
    ] as CASEntryPoint[];

    const filtered = (new AnalyzerOrchestrator() as any).filterPrimaryProductEntryPoints(
      entries,
      [...generated, ...authored],
      root,
    );

    expect(filtered.map((entry: CASEntryPoint) => entry.id)).toEqual(['authored-entry']);
  });
});
