/**
 * COMPETITOR SCORECARD (#97) — a clean, shareable A/B/C report of Klauro vs each
 * competitor, generated by running the head-to-head benches THROUGH THE PRODUCT.
 *
 * This is a BLACKBOX consumer of the gauntlet's own head-to-head runners. Every
 * Klauro number it reports comes from analyzeForBench (gauntlet/product-analysis),
 * which routes to KLAURO_BENCH_ANALYZER_URL when set — so pointing that at
 * https://mcp.klauro.com scores the DEPLOYED product. This file never imports the
 * analyzer engine and never touches a model; it only invokes runners and normalizes
 * their structured reports.
 *
 * The three camps (the shareable narrative):
 *   - Camp A — vs codebase-memory (DeusData): the routes / behavioral-diff head-to-
 *     heads, plus any full-grid cell whose best competitor is codebase-memory.
 *     Target = tie-or-beat (Klauro never loses).
 *   - Camp B — vs structural indexers (ripgrep / ast-grep / ctags / scip /
 *     stack-graphs / embeddings): the primitive who-calls + cross-repo links +
 *     full-grid Camp-B arms. Target = win.
 *   - Camp C — comprehension / out-of-category (framework routes, ORM relations,
 *     component render tree, comprehension facts). Target = always win.
 *
 * Every runner returns a different structured shape; normalizeRows() below maps each
 * into the one common ScorecardRow type. The runners are INJECTABLE (opts.runners)
 * so the live run and the unit test share exactly one code path — the test injects
 * stub reports (no network, no analyzeForBench), the CLI injects the real ones.
 */

import * as path from 'path';
import type { ArmResult, WinVerdict } from './report-schema';

// Real runners (defaults). Imported lazily-typed so the test can inject stubs
// without any of these executing.
import { runRouteFactsBench, type FrameworkBenchResult } from './framework-bench';
import { runCallersBench, type PrimitiveBenchResult } from './primitive-bench';
import { runWasCrossRepoBench, type WasBenchResult } from './was-bench';
import { runOrmRelationsBench, type OrmBenchResult } from './orm-bench';
import { runComponentTreeBench, type ComponentBenchResult } from './component-bench';
import { buildCampCRoutesVsCbmReport, type CampCRoutesVsCbmReport } from './camp-c-routes-cbm';
import { buildDepthBehavioralDiffReport, type DepthBehavioralDiffReport } from './depth-behavioral-diff-bench';
import { buildFullGrid, type FullGridReport, type GridCell } from './full-grid';

// ---------------------------------------------------------------------------
// The common row + report types.
// ---------------------------------------------------------------------------

export type Camp = 'A' | 'B' | 'C';
export type Verdict = 'win' | 'tie' | 'loss';

export interface ScorecardRow {
  /** Which camp this row belongs to (A = vs codebase-memory, B = vs structural
   *  indexers, C = comprehension / out-of-category). */
  camp: Camp;
  /** The bench + fixture, e.g. "framework-routes: express-routes". */
  scenario: string;
  /** The task/question the scenario answers, e.g. "who-calls". */
  task: string;
  /** The metric the verdict is scored on, e.g. "route-F1" / "tokens". */
  metric: string;
  /** Klauro's score on this scenario, 0..1 (F1 / quality fraction), or null when
   *  the runner only exposes a pass/verdict and no numeric score. */
  klauro_score: number | null;
  /** The strongest competitor on this scenario. */
  best_competitor: string;
  /** That competitor's score, 0..1, or null when out-of-category (no score). */
  best_competitor_score: number | null;
  /** win = Klauro strictly ahead / competitor cannot answer; tie = matched at the
   *  ceiling; loss = a competitor beat Klauro (a bug — surfaced, never hidden). */
  verdict: Verdict;
}

export interface CampSummary {
  camp: Camp;
  /** The camp's shareable name. */
  label: string;
  /** The camp's target posture. */
  target: string;
  rows: ScorecardRow[];
  wins: number;
  ties: number;
  losses: number;
}

export interface CompetitorScorecard {
  endpoint: string;
  timestamp: string;
  camps: CampSummary[];
  totals: { wins: number; ties: number; losses: number; scenarios: number };
  /** True when no camp recorded a loss — the headline assertion. */
  zeroLosses: boolean;
}

// ---------------------------------------------------------------------------
// Camp classification — which competitor lives in which camp.
// ---------------------------------------------------------------------------

const CAMP_A_COMPETITORS = new Set(['codebase-memory', 'codebase-memory-mcp', 'cbm']);
const CAMP_B_COMPETITORS = new Set([
  'ripgrep', 'ast-grep', 'ctags', 'scip-typescript', 'scip', 'stack-graphs',
  'embeddings-nomic', 'embeddings', 'nomic', 'all-minilm',
]);

function campForCompetitor(competitor: string): Camp {
  const c = competitor.toLowerCase();
  if (CAMP_A_COMPETITORS.has(c)) return 'A';
  if (CAMP_B_COMPETITORS.has(c) || c.startsWith('embeddings-')) return 'B';
  // Anything else (out-of-category "none", framework/library facts) is comprehension.
  return 'C';
}

// ---------------------------------------------------------------------------
// Arm-based benches (framework / primitive / was / orm / component) — normalize
// the shared { arms, verdict } shape into a ScorecardRow.
// ---------------------------------------------------------------------------

interface ArmBenchResult { fixture: string; arms: ArmResult[]; verdict: WinVerdict; }

/** The strongest ATTEMPTED non-klauro arm (highest quality); falls back to the
 *  first non-klauro arm when none attempted (out-of-category "cannot answer"). */
function bestCompetitorArm(arms: ArmResult[]): { arm: ArmResult | null; attempted: boolean } {
  const others = arms.filter(a => a.arm_id !== 'klauro');
  const attempted = others.filter(a => a.attempted);
  if (attempted.length) {
    const best = attempted.reduce((a, b) =>
      (b.metrics.quality ?? 0) > (a.metrics.quality ?? 0) ? b : a);
    return { arm: best, attempted: true };
  }
  return { arm: others[0] ?? null, attempted: false };
}

/** Map a WinVerdict + best competitor into the scorecard's win/tie/loss. */
function verdictFromWin(win: WinVerdict): Verdict {
  if (!win.klauro_wins) return 'loss';
  return win.quality_tied_at_ceiling ? 'tie' : 'win';
}

function rowFromArmBench(
  benchLabel: string,
  task: string,
  metric: string,
  result: ArmBenchResult,
): ScorecardRow {
  const klauro = result.arms.find(a => a.arm_id === 'klauro');
  const { arm: bestArm, attempted } = bestCompetitorArm(result.arms);
  const camp = bestArm ? campForCompetitor(bestArm.arm_id) : 'C';
  const klauroScore = typeof klauro?.metrics.quality === 'number' ? klauro.metrics.quality / 100 : null;
  // Out-of-category competitors are un-attempted — they cannot produce a score, so
  // report null rather than a misleading 0.
  const competitorScore =
    bestArm && attempted && typeof bestArm.metrics.quality === 'number'
      ? bestArm.metrics.quality / 100
      : null;
  return {
    camp,
    scenario: `${benchLabel}: ${result.fixture}`,
    task,
    metric,
    klauro_score: klauroScore,
    best_competitor: bestArm?.arm_id ?? 'none',
    best_competitor_score: competitorScore,
    verdict: verdictFromWin(result.verdict),
  };
}

// ---------------------------------------------------------------------------
// codebase-memory aggregate benches — normalize per-framework / per-case rows.
// ---------------------------------------------------------------------------

function rowsFromCampCRoutes(report: CampCRoutesVsCbmReport): ScorecardRow[] {
  return report.results.map(r => ({
    camp: 'A' as Camp,
    scenario: `camp-c-routes-vs-cbm: ${r.fixture}`,
    task: 'route-facts',
    metric: 'route-F1',
    klauro_score: r.klauroF1,
    best_competitor: 'codebase-memory',
    best_competitor_score: r.cbmF1,
    // The bench's own verdict: 'win' | 'tie-ceiling' | 'loss'.
    verdict: r.verdict === 'tie-ceiling' ? 'tie' : r.verdict,
  }));
}

function rowsFromBehavioralDiff(report: DepthBehavioralDiffReport): ScorecardRow[] {
  return report.results.map(r => ({
    camp: 'A' as Camp,
    scenario: `depth-behavioral-diff-vs-cbm: ${r.fixture}`,
    task: 'behavioral-delta',
    metric: 'behavior-F1',
    klauro_score: r.klauroF1,
    best_competitor: 'codebase-memory',
    best_competitor_score: r.cbmF1,
    // The bench's own verdict: 'win' | 'tie' | 'loss'.
    verdict: r.verdict,
  }));
}

// ---------------------------------------------------------------------------
// Full-grid — the aggregate matrix: every language/framework/library cell, Klauro
// vs the best competitor. Normalize each covered cell (skip uncovered gaps).
// ---------------------------------------------------------------------------

function verdictFromGrid(v: GridCell['verdict']): Verdict {
  if (v === 'loss') return 'loss';
  if (v === 'ceiling-tie') return 'tie';
  return 'win';
}

function rowsFromFullGrid(report: FullGridReport): ScorecardRow[] {
  const rows: ScorecardRow[] = [];
  for (const cell of report.cells) {
    if (cell.verdict === 'uncovered') continue; // honest gap, not a scorecard row.
    // Best competitor for the cell = the strongest arm that actually ran. Where the
    // grid recorded no arms (pure out-of-category), fall back to 'none' -> Camp C.
    const best = cell.armsRan.length ? cell.armsRan[0] : 'none';
    // For structural-retrieval cells the arm is the embedding model tag.
    const camp = cell.armsRan.length
      ? cell.armsRan.map(campForCompetitor).sort()[0] // A < B < C: report the toughest camp the cell touches
      : 'C';
    rows.push({
      camp,
      scenario: `full-grid: ${cell.rowKind}/${cell.row} [${cell.metric}]`,
      task: cell.metric,
      metric: 'cell-F1',
      klauro_score: cell.klauroF1,
      best_competitor: best,
      best_competitor_score: cell.competitorBestF1,
      verdict: verdictFromGrid(cell.verdict),
    });
  }
  return rows;
}

// ---------------------------------------------------------------------------
// The injectable runner set. Each returns already-normalized ScorecardRows so the
// live run and the test share one code path — the test injects stubs, the CLI the
// real product-backed runs.
// ---------------------------------------------------------------------------

const FIXTURES = path.resolve(__dirname, '../../fixtures');

export interface ScorecardRunners {
  frameworkRoutes: () => Promise<ScorecardRow[]>;
  primitiveCallers: () => Promise<ScorecardRow[]>;
  campCRoutes: () => Promise<ScorecardRow[]>;
  behavioralDiff: () => Promise<ScorecardRow[]>;
  wasCrossRepo: () => Promise<ScorecardRow[]>;
  ormRelations: () => Promise<ScorecardRow[]>;
  componentTree: () => Promise<ScorecardRow[]>;
  fullGrid: () => Promise<ScorecardRow[]>;
}

/** The default (live, product-backed) runner set. Each picks a representative
 *  fixture for the arm-based benches and reads the aggregate for the rest. */
export function defaultRunners(): ScorecardRunners {
  return {
    frameworkRoutes: async () => [
      rowFromArmBench('framework-routes', 'route-facts', 'quality-F1',
        (await runRouteFactsBench(path.join(FIXTURES, 'framework-bench', 'express-routes'))) as FrameworkBenchResult),
    ],
    primitiveCallers: async () => [
      rowFromArmBench('primitive-who-calls', 'who-calls', 'caller-F1',
        (await runCallersBench(path.join(FIXTURES, 'primitive-bench', 'callers-py'), { heavyArms: true })) as PrimitiveBenchResult),
    ],
    campCRoutes: async () => rowsFromCampCRoutes(await buildCampCRoutesVsCbmReport()),
    behavioralDiff: async () => rowsFromBehavioralDiff(await buildDepthBehavioralDiffReport()),
    wasCrossRepo: async () => [
      rowFromArmBench('was-cross-repo', 'cross-repo-links', 'link-F1',
        (await runWasCrossRepoBench(path.join(FIXTURES, 'was-bench', 'ui-api-worker'))) as WasBenchResult),
    ],
    ormRelations: async () => [
      rowFromArmBench('orm-relations', 'orm-relations', 'relation-F1',
        (await runOrmRelationsBench(path.join(FIXTURES, 'orm-bench', 'drizzle-rel'))) as OrmBenchResult),
    ],
    componentTree: async () => [
      rowFromArmBench('component-tree', 'component-tree', 'render-F1',
        (await runComponentTreeBench(path.join(FIXTURES, 'component-bench', 'react-tree'))) as ComponentBenchResult),
    ],
    fullGrid: async () => rowsFromFullGrid(await buildFullGrid()),
  };
}

// ---------------------------------------------------------------------------
// The generator.
// ---------------------------------------------------------------------------

export interface GenerateScorecardOptions {
  /** Injected runner set — defaults to the live, product-backed runners. The test
   *  injects stubs here so no network / analyzeForBench call is ever made. */
  runners?: Partial<ScorecardRunners>;
  /** Report timestamp (ISO). Passed in so nothing calls Date.now() at import. */
  timestamp?: string;
  /** The analyzer endpoint the Klauro scores came from (for the header). Defaults
   *  to KLAURO_BENCH_ANALYZER_URL or the in-process bench server. */
  endpoint?: string;
}

const CAMP_META: Record<Camp, { label: string; target: string }> = {
  A: { label: 'Camp A — vs codebase-memory (DeusData)', target: 'tie-or-beat (Klauro never loses)' },
  B: { label: 'Camp B — vs structural indexers (ripgrep / ast-grep / ctags / scip / stack-graphs / embeddings)', target: 'win' },
  C: { label: 'Camp C — comprehension / out-of-category (routes, ORM, component tree, comprehension facts)', target: 'always win' },
};

export async function generateCompetitorScorecard(
  opts: GenerateScorecardOptions = {},
): Promise<CompetitorScorecard> {
  const runners: ScorecardRunners = { ...defaultRunners(), ...opts.runners };
  const timestamp = opts.timestamp ?? new Date().toISOString();
  const endpoint =
    opts.endpoint ?? process.env.KLAURO_BENCH_ANALYZER_URL ?? 'in-process bench analyzer (offline)';

  // Run every runner; each returns already-normalized rows. A runner that throws
  // (e.g. a competitor binary absent) contributes no rows rather than aborting.
  const groups = await Promise.all(
    (Object.keys(runners) as (keyof ScorecardRunners)[]).map(async key => {
      try {
        return await runners[key]();
      } catch {
        return [] as ScorecardRow[];
      }
    }),
  );
  const rows = groups.flat();

  const camps: CampSummary[] = (['A', 'B', 'C'] as Camp[]).map(camp => {
    const campRows = rows.filter(r => r.camp === camp);
    return {
      camp,
      label: CAMP_META[camp].label,
      target: CAMP_META[camp].target,
      rows: campRows,
      wins: campRows.filter(r => r.verdict === 'win').length,
      ties: campRows.filter(r => r.verdict === 'tie').length,
      losses: campRows.filter(r => r.verdict === 'loss').length,
    };
  });

  const totals = {
    wins: camps.reduce((a, c) => a + c.wins, 0),
    ties: camps.reduce((a, c) => a + c.ties, 0),
    losses: camps.reduce((a, c) => a + c.losses, 0),
    scenarios: rows.length,
  };

  return {
    endpoint,
    timestamp,
    camps,
    totals,
    zeroLosses: totals.losses === 0,
  };
}

// ---------------------------------------------------------------------------
// Markdown rendering.
// ---------------------------------------------------------------------------

function fmtScore(s: number | null): string {
  return s == null ? '—' : s.toFixed(2);
}

function verdictBadge(v: Verdict): string {
  return v === 'win' ? 'WIN' : v === 'tie' ? 'TIE' : 'LOSS';
}

export function renderScorecardMarkdown(report: CompetitorScorecard): string {
  const lines: string[] = [];
  lines.push('# Klauro Competitor Scorecard');
  lines.push('');
  lines.push(`- Endpoint: \`${report.endpoint}\``);
  lines.push(`- Generated: ${report.timestamp}`);
  lines.push('');

  for (const camp of report.camps) {
    lines.push(`## ${camp.label}`);
    lines.push('');
    lines.push(`Target: ${camp.target} — ${camp.wins} win / ${camp.ties} tie / ${camp.losses} loss`);
    lines.push('');
    if (camp.rows.length === 0) {
      lines.push('_No scenarios recorded._');
      lines.push('');
      continue;
    }
    lines.push('| Scenario | Metric | Klauro | Best competitor | Verdict |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const r of camp.rows) {
      const comp = r.best_competitor_score == null
        ? `${r.best_competitor} (n/a)`
        : `${r.best_competitor} ${fmtScore(r.best_competitor_score)}`;
      lines.push(
        `| ${r.scenario} | ${r.metric} | ${fmtScore(r.klauro_score)} | ${comp} | ${verdictBadge(r.verdict)} |`,
      );
    }
    lines.push('');
  }

  const t = report.totals;
  lines.push('## Summary');
  lines.push('');
  lines.push(`Total: ${t.wins} win / ${t.ties} tie / ${t.losses} loss across ${t.scenarios} scenarios.`);
  lines.push('');
  lines.push(
    report.zeroLosses
      ? '**Zero losses** — Klauro ties-or-beats every competitor in every camp.'
      : `**${t.losses} loss(es)** — a Klauro bug to fix; surfaced, never hidden.`,
  );
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// CLI entry (guarded) — tsx src/gauntlet/competitor-scorecard.ts [--out p] [--md p]
// ---------------------------------------------------------------------------

function parseArgs(argv: string[]): { out?: string; md?: string } {
  const out: { out?: string; md?: string } = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--out') out.out = argv[++i];
    else if (argv[i] === '--md') out.md = argv[++i];
  }
  return out;
}

async function main(): Promise<void> {
  // fs-extra is CJS; a dynamic ESM import exposes its API on `.default`.
  const fsMod = await import('fs-extra');
  const fs: typeof import('fs-extra') = (fsMod as any).default ?? fsMod;
  const { out, md } = parseArgs(process.argv.slice(2));
  const report = await generateCompetitorScorecard({ timestamp: new Date().toISOString() });
  const markdown = renderScorecardMarkdown(report);

  if (out) {
    await fs.writeJson(out, report, { spaces: 2 });
    console.error(`[scorecard] wrote JSON -> ${out}`);
  }
  if (md) {
    await fs.writeFile(md, markdown, 'utf8');
    console.error(`[scorecard] wrote markdown -> ${md}`);
  }
  if (!out && !md) {
    // Default: emit the markdown to stdout so it's pipe-able.
    process.stdout.write(markdown);
  }
}

// Only run when executed directly, never on import (the test imports this module).
if (require.main === module) {
  main().catch(err => {
    console.error('[scorecard] failed:', err);
    process.exit(1);
  });
}
