static MARKERS: &[&str] = &[
    "@generated",
    "<auto-generated",
    "code generated by",
    "do not edit",
    "do not modify",
    "generated by the protocol buffer compiler",
    "this file is generated",
    "this file was automatically generated",
    "this file was generated",
];

static COMMENT_STARTS: &[&str] = &["//", "/*", "*", "#", "--", "<!--", ";", "%", "'''", "\"\"\""];

const BANNER_LINES: usize = 5;

pub fn is_generated(source: &[u8]) -> bool {
    let window = &source[..source.len().min(4096)];
    let text = String::from_utf8_lossy(window);
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .take(BANNER_LINES)
        .any(is_banner)
}

fn is_banner(line: &str) -> bool {
    let trimmed = line.trim_start().trim_start_matches(['\u{feff}', '\u{200b}']);
    let body = match trimmed.strip_prefix("#!") {
        Some(_) => return false,
        None => trimmed,
    };
    if !COMMENT_STARTS
        .iter()
        .any(|start| body.starts_with(start))
    {
        return false;
    }
    let lowered = body.to_ascii_lowercase();
    MARKERS.iter().any(|marker| lowered.contains(marker))
}
