pub static SOURCE_EXTENSIONS: &[&str] = &[
    "adb",
    "ads",
    "agda",
    "apex",
    "asd",
    "asm",
    "astro",
    "awk",
    "bal",
    "bash",
    "bat",
    "bib",
    "bicep",
    "bicepparam",
    "blade.php",
    "bzl",
    "c",
    "c++",
    "cairo",
    "capnp",
    "cbl",
    "cc",
    "ccp",
    "cfg",
    "circom",
    "cjs",
    "cl",
    "clar",
    "clj",
    "cljc",
    "cljs",
    "cls",
    "cmake",
    "cmd",
    "cob",
    "comp",
    "conf",
    "cpon",
    "cpp",
    "cpy",
    "cr",
    "cs",
    "csproj",
    "css",
    "cu",
    "cue",
    "cuh",
    "cxx",
    "d",
    "dart",
    "ddl",
    "dhall",
    "di",
    "dml",
    "dockerfile",
    "dpr",
    "dts",
    "dtsi",
    "edn",
    "elm",
    "erl",
    "ex",
    "exs",
    "f",
    "f03",
    "f08",
    "f77",
    "f90",
    "f95",
    "fc",
    "fidl",
    "fish",
    "fnl",
    "for",
    "frag",
    "fs",
    "fsi",
    "fsproj",
    "fsx",
    "fun",
    "func",
    "fx",
    "fxh",
    "gd",
    "gdshader",
    "geom",
    "gleam",
    "glsl",
    "gn",
    "gni",
    "go",
    "gql",
    "gr",
    "gradle",
    "graphql",
    "graphqls",
    "gren",
    "groovy",
    "gvy",
    "h",
    "ha",
    "hack",
    "handlebars",
    "hbs",
    "hck",
    "hcl",
    "hh",
    "hlsl",
    "hlsli",
    "hocon",
    "hpp",
    "hrl",
    "hs",
    "htm",
    "html",
    "hx",
    "hxsl",
    "hxx",
    "inc",
    "ipp",
    "iss",
    "janet",
    "java",
    "jl",
    "jmd",
    "js",
    "jsonnet",
    "jsx",
    "kconfig",
    "kdl",
    "ksh",
    "kt",
    "kts",
    "less",
    "lhs",
    "libsonnet",
    "liquid",
    "lisp",
    "ll",
    "lsp",
    "ltx",
    "lua",
    "luau",
    "m",
    "mak",
    "markdown",
    "md",
    "mdx",
    "mjs",
    "mk",
    "ml",
    "mli",
    "mlir",
    "mll",
    "mly",
    "mm",
    "move",
    "ncl",
    "nim",
    "nimble",
    "nims",
    "nix",
    "nomad",
    "nr",
    "nsi",
    "nut",
    "odin",
    "p4",
    "pas",
    "php",
    "pkl",
    "pl",
    "plist",
    "pm",
    "pod",
    "pony",
    "pp",
    "prisma",
    "promql",
    "proto",
    "prql",
    "ps1",
    "psd1",
    "psm1",
    "purs",
    "py",
    "ql",
    "qll",
    "r",
    "rake",
    "rb",
    "re",
    "rego",
    "rei",
    "res",
    "resi",
    "rkt",
    "rktl",
    "rmd",
    "ron",
    "rq",
    "rs",
    "s",
    "sass",
    "sbt",
    "sc",
    "scala",
    "scd",
    "scm",
    "scss",
    "sh",
    "sig",
    "slang",
    "sld",
    "smali",
    "smithy",
    "sml",
    "sol",
    "sp",
    "sparql",
    "sq",
    "sql",
    "sqm",
    "ss",
    "star",
    "sty",
    "sv",
    "svelte",
    "svh",
    "svi",
    "sw",
    "swift",
    "t",
    "tact",
    "tcl",
    "td",
    "templ",
    "tesc",
    "tese",
    "tex",
    "tf",
    "tfvars",
    "thrift",
    "tk",
    "tla",
    "tpp",
    "trigger",
    "ts",
    "tsx",
    "twig",
    "typ",
    "v",
    "vala",
    "vapi",
    "vbproj",
    "vert",
    "vh",
    "vhd",
    "vhdl",
    "vim",
    "vimrc",
    "vue",
    "w",
    "wast",
    "wat",
    "wgsl",
    "wren",
    "wsdl",
    "xaml",
    "xhtml",
    "xml",
    "xsd",
    "xsl",
    "xslt",
    "yaml",
    "yar",
    "yara",
    "yml",
    "zig",
    "zsh",
];

pub static MANIFEST_NAMES: &[&str] = &[
    ".hhconfig",
    "ballerina.toml",
    "bsconfig.json",
    "build",
    "build.bazel",
    "build.gradle",
    "build.gradle.kts",
    "build.sbt",
    "build.zig",
    "build.zig.zon",
    "cargo.toml",
    "clarinet.toml",
    "cmakelists.txt",
    "composer.json",
    "containerfile",
    "corral.json",
    "cpanfile",
    "default.nix",
    "deps.edn",
    "description",
    "dockerfile",
    "dub.json",
    "dub.sdl",
    "dune",
    "dune-project",
    "elm.json",
    "flake.nix",
    "forc.toml",
    "foundry.toml",
    "gemfile",
    "gemfile.lock",
    "gleam.toml",
    "gnumakefile",
    "go.mod",
    "hardhat.config.js",
    "hardhat.config.ts",
    "haxelib.json",
    "info.rkt",
    "makefile",
    "makefile.pl",
    "meson.build",
    "meson_options.txt",
    "mix.exs",
    "move.toml",
    "namespace",
    "nargo.toml",
    "package.json",
    "package.swift",
    "package.yaml",
    "pipfile",
    "pom.xml",
    "project.clj",
    "project.godot",
    "project.toml",
    "pubspec.yaml",
    "pyproject.toml",
    "qlpack.yml",
    "rebar.config",
    "rescript.json",
    "rockspec",
    "routes",
    "scarb.toml",
    "settings.gradle",
    "settings.gradle.kts",
    "setup.py",
    "sfdx-project.json",
    "shard.yml",
    "shell.nix",
    "spago.dhall",
    "spago.yaml",
    "stack.yaml",
    "truffle-config.js",
    "workspace",
    "workspace.bazel",
];

pub static MANIFEST_EXTENSIONS: &[&str] = &[
    "cabal",
    "csproj",
    "fsproj",
    "gemspec",
    "sln",
    "vbproj",
];

pub static MANIFEST_PATTERNS: &[&str] = &[
    "^.*\\.routes$",
    "^requirements.*\\.txt$",
];

pub static SKIPPED_DIRECTORIES: &[&str] = &[
    ".angular",
    ".cache",
    ".claude",
    ".codex",
    ".dart_tool",
    ".git",
    ".godot",
    ".gradle",
    ".gradle-cache",
    ".mypy_cache",
    ".next",
    ".nuxt",
    ".parcel-cache",
    ".pnpm-store",
    ".pytest_cache",
    ".ruff_cache",
    ".scannerwork",
    ".sourcemaps",
    ".svelte-kit",
    ".terraform",
    ".tox",
    ".turbo",
    ".venv",
    ".vite",
    ".yarn",
    "Generated",
    "Pods",
    "__fixtures__",
    "__pycache__",
    "__tests__",
    "build",
    "build-out",
    "build_out",
    "cas-tests",
    "cmake-build-debug",
    "cmake-build-release",
    "dist",
    "env",
    "external-crates",
    "fixtures",
    "generated",
    "node_modules",
    "obj",
    "out",
    "site-packages",
    "storybook-build",
    "storybook-static",
    "target",
    "testdata",
    "third-party",
    "third_party",
    "vendor",
    "vendored",
    "vendors",
    "venv",
];

pub static LANGUAGE_BY_MANIFEST: &[(&str, &str)] = &[
    (".hhconfig", "hack"),
    ("build", "bazel"),
    ("build.bazel", "bazel"),
    ("build.sbt", "scala"),
    ("build.zig", "zig"),
    ("build.zig.zon", "zig"),
    ("cmakelists.txt", "cmake"),
    ("containerfile", "dockerfile"),
    ("cpanfile", "perl"),
    ("default.nix", "nix"),
    ("deps.edn", "clojure"),
    ("description", "r"),
    ("dockerfile", "dockerfile"),
    ("dub.sdl", "d"),
    ("dune", "ocaml"),
    ("dune-project", "ocaml"),
    ("flake.nix", "nix"),
    ("gemfile", "ruby"),
    ("gnumakefile", "make"),
    ("go.mod", "go"),
    ("hardhat.config.js", "solidity"),
    ("hardhat.config.ts", "solidity"),
    ("info.rkt", "racket"),
    ("makefile", "make"),
    ("makefile.pl", "perl"),
    ("meson_options.txt", "meson"),
    ("meson.build", "meson"),
    ("mix.exs", "elixir"),
    ("namespace", "r"),
    ("package.swift", "swift"),
    ("pipfile", "python"),
    ("project.clj", "clojure"),
    ("project.godot", "gdscript"),
    ("rebar.config", "erlang"),
    ("rockspec", "lua"),
    ("routes", "scala"),
    ("settings.gradle", "kotlin"),
    ("settings.gradle.kts", "kotlin"),
    ("setup.py", "python"),
    ("shell.nix", "nix"),
    ("spago.dhall", "purescript"),
    ("truffle-config.js", "solidity"),
    ("workspace", "bazel"),
    ("workspace.bazel", "bazel"),
];

pub static LANGUAGE_BY_EXTENSION: &[(&str, &str)] = &[
    ("adb", "ada"),
    ("ads", "ada"),
    ("agda", "agda"),
    ("apex", "apex_page"),
    ("asd", "commonlisp"),
    ("asm", "nasm"),
    ("astro", "astro_lang"),
    ("awk", "awk"),
    ("bal", "ballerina"),
    ("bash", "shell"),
    ("bat", "installer_scripts"),
    ("bib", "latex"),
    ("bicep", "bicep"),
    ("bicepparam", "bicep"),
    ("blade.php", "blade"),
    ("bzl", "bazel"),
    ("c", "c"),
    ("c++", "cpp"),
    ("cairo", "cairo"),
    ("capnp", "capnp"),
    ("cbl", "cobol"),
    ("cc", "cpp"),
    ("ccp", "cobol"),
    ("cfg", "configuration"),
    ("circom", "circom"),
    ("cjs", "javascript"),
    ("cl", "opencl"),
    ("cl", "commonlisp"),
    ("clar", "clarity"),
    ("clj", "clojure"),
    ("cljc", "clojure"),
    ("cljs", "clojure"),
    ("cls", "apex"),
    ("cmake", "cmake"),
    ("cmd", "installer_scripts"),
    ("cob", "cobol"),
    ("comp", "glsl"),
    ("conf", "configuration"),
    ("cpon", "cpon"),
    ("cpp", "cpp"),
    ("cpy", "cobol"),
    ("cr", "crystal"),
    ("cs", "csharp"),
    ("csproj", "xml"),
    ("css", "css"),
    ("cu", "cuda"),
    ("cue", "cue"),
    ("cuh", "cuda"),
    ("cxx", "cpp"),
    ("d", "d"),
    ("dart", "dart"),
    ("ddl", "sql"),
    ("ddl", "sql_more"),
    ("dhall", "dhall"),
    ("di", "d"),
    ("dml", "sql_more"),
    ("dockerfile", "dockerfile"),
    ("dpr", "pascal"),
    ("dts", "devicetree"),
    ("dtsi", "devicetree"),
    ("edn", "clojure"),
    ("elm", "elm"),
    ("erl", "erlang"),
    ("ex", "elixir"),
    ("exs", "elixir"),
    ("f", "fortran"),
    ("f03", "fortran"),
    ("f08", "fortran"),
    ("f77", "fortran"),
    ("f90", "fortran"),
    ("f95", "fortran"),
    ("fc", "func"),
    ("fidl", "fidl"),
    ("fish", "fish"),
    ("fnl", "fennel"),
    ("for", "fortran"),
    ("frag", "glsl"),
    ("fs", "fsharp"),
    ("fsi", "fsharp"),
    ("fsproj", "xml"),
    ("fsx", "fsharp"),
    ("fun", "sml"),
    ("func", "func"),
    ("fx", "hlsl"),
    ("fxh", "hlsl"),
    ("gd", "gdscript"),
    ("gdshader", "gdshader"),
    ("geom", "glsl"),
    ("gleam", "gleam"),
    ("glsl", "glsl"),
    ("gn", "gn"),
    ("gni", "gn"),
    ("go", "go"),
    ("gql", "graphql"),
    ("gr", "grain"),
    ("gradle", "groovy"),
    ("graphql", "graphql"),
    ("graphqls", "graphql"),
    ("gren", "gren"),
    ("groovy", "groovy"),
    ("gvy", "groovy"),
    ("h", "c"),
    ("ha", "hare"),
    ("hack", "hack"),
    ("handlebars", "glimmer"),
    ("hbs", "glimmer"),
    ("hck", "hack"),
    ("hcl", "hcl"),
    ("hh", "cpp"),
    ("hlsl", "hlsl"),
    ("hlsli", "hlsl"),
    ("hocon", "hocon"),
    ("hpp", "cpp"),
    ("hrl", "erlang"),
    ("hs", "haskell"),
    ("htm", "html"),
    ("html", "html"),
    ("hx", "haxe"),
    ("hxsl", "haxe"),
    ("hxx", "cpp"),
    ("inc", "sourcepawn"),
    ("ipp", "cpp"),
    ("iss", "installer_scripts"),
    ("janet", "janet"),
    ("java", "java"),
    ("jl", "julia"),
    ("jmd", "julia_more"),
    ("js", "javascript"),
    ("jsonnet", "jsonnet"),
    ("jsx", "javascript"),
    ("kconfig", "kconfig"),
    ("kdl", "kdl"),
    ("ksh", "shell"),
    ("kt", "kotlin"),
    ("kts", "kotlin"),
    ("less", "css"),
    ("lhs", "haskell"),
    ("libsonnet", "jsonnet"),
    ("liquid", "liquid"),
    ("lisp", "commonlisp"),
    ("ll", "llvm"),
    ("lsp", "commonlisp"),
    ("ltx", "latex"),
    ("lua", "lua"),
    ("luau", "luau"),
    ("m", "objc"),
    ("mak", "make"),
    ("markdown", "markdown"),
    ("md", "markdown"),
    ("mdx", "markdown"),
    ("mjs", "javascript"),
    ("mk", "make"),
    ("ml", "ocaml"),
    ("mli", "ocaml"),
    ("mlir", "mlir"),
    ("mll", "ocaml_extra"),
    ("mly", "ocaml_extra"),
    ("mm", "objc"),
    ("move", "move"),
    ("ncl", "nickel"),
    ("nim", "nim"),
    ("nimble", "nim"),
    ("nims", "nim"),
    ("nix", "nix"),
    ("nomad", "hcl"),
    ("nr", "noir"),
    ("nsi", "installer_scripts"),
    ("nut", "squirrel"),
    ("odin", "odin"),
    ("p4", "p4"),
    ("pas", "pascal"),
    ("php", "php"),
    ("pkl", "pkl"),
    ("pl", "perl"),
    ("plist", "xml"),
    ("pm", "perl"),
    ("pod", "perl_pod"),
    ("pony", "pony"),
    ("pp", "pascal"),
    ("pp", "puppet"),
    ("prisma", "prisma"),
    ("promql", "promql"),
    ("proto", "proto"),
    ("prql", "prql"),
    ("ps1", "powershell"),
    ("psd1", "powershell"),
    ("psm1", "powershell"),
    ("purs", "purescript"),
    ("py", "python"),
    ("ql", "ql"),
    ("qll", "ql"),
    ("r", "r"),
    ("rake", "ruby"),
    ("rb", "ruby"),
    ("re", "reason"),
    ("rego", "rego"),
    ("rei", "reason"),
    ("res", "rescript"),
    ("resi", "rescript"),
    ("rkt", "racket"),
    ("rktl", "racket"),
    ("rmd", "r"),
    ("ron", "ron"),
    ("rq", "sparql"),
    ("rs", "rust"),
    ("s", "nasm"),
    ("sass", "css"),
    ("sbt", "scala"),
    ("sc", "scala"),
    ("scala", "scala"),
    ("scd", "supercollider"),
    ("scm", "scheme"),
    ("scss", "css"),
    ("sh", "shell"),
    ("sig", "sml"),
    ("slang", "slang"),
    ("sld", "scheme"),
    ("smali", "smali"),
    ("smithy", "smithy"),
    ("sml", "sml"),
    ("sol", "solidity"),
    ("sp", "sourcepawn"),
    ("sparql", "sparql"),
    ("sq", "sql"),
    ("sql", "sql"),
    ("sqm", "sql"),
    ("ss", "scheme"),
    ("star", "bazel"),
    ("star", "starlark"),
    ("sty", "latex"),
    ("sv", "verilog"),
    ("sv", "systemverilog"),
    ("svelte", "svelte"),
    ("svh", "verilog"),
    ("svh", "systemverilog"),
    ("svi", "systemverilog"),
    ("sw", "sway"),
    ("swift", "swift"),
    ("t", "perl"),
    ("tact", "tact"),
    ("tcl", "tcl"),
    ("td", "tablegen"),
    ("templ", "templ"),
    ("tesc", "glsl"),
    ("tese", "glsl"),
    ("tex", "latex"),
    ("tf", "terraform"),
    ("tfvars", "terraform"),
    ("thrift", "thrift"),
    ("tk", "tcl"),
    ("tla", "tlaplus"),
    ("tpp", "cpp"),
    ("trigger", "apex"),
    ("ts", "typescript"),
    ("tsx", "typescript"),
    ("twig", "twig"),
    ("typ", "typst"),
    ("v", "verilog"),
    ("vala", "vala"),
    ("vapi", "vala"),
    ("vbproj", "xml"),
    ("vert", "glsl"),
    ("vh", "verilog"),
    ("vhd", "vhdl"),
    ("vhdl", "vhdl"),
    ("vim", "vim"),
    ("vimrc", "vim"),
    ("vue", "vue"),
    ("w", "wing"),
    ("wast", "wat"),
    ("wat", "wat"),
    ("wgsl", "wgsl"),
    ("wren", "wren"),
    ("wsdl", "soap-contract"),
    ("xaml", "csharp"),
    ("xhtml", "html"),
    ("xml", "xml"),
    ("xsd", "xml"),
    ("xsd", "soap-contract"),
    ("xsl", "xml"),
    ("xslt", "xml"),
    ("yaml", "configuration"),
    ("yar", "yara"),
    ("yara", "yara"),
    ("yml", "configuration"),
    ("zig", "zig"),
    ("zsh", "shell"),
];
